version: '3.8'
services:
  backend:
    build: ./
    container_name: 'apic'
    ports:
      - 3000:5000
    volumes:
      - type: bind
        source: ./
        target: /app
  db:
    image: 'postgres'
    restart: always
    container_name: 'pc'
    ports:
      - 3001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  pgdata:
