version: '3.8'
services:
  backend:
    build: ./
    ports:
      - 3000:5000
    volumes:
      - type: bind
        source: ./
        target: /app
      - nodemodules:/app/node_modules
    container_name: cities

volumes:
  nodemodules:
